# Generated by Django 4.1.2 on 2023-06-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alimentos_collares_juguetes_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='juguetes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='venta'),
        ),
    ]
