# Generated by Django 4.1.2 on 2023-06-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_juguetes_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/alimentos'),
        ),
        migrations.AddField(
            model_name='collares',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/collares'),
        ),
        migrations.AlterField(
            model_name='juguetes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/juguetes'),
        ),
    ]
