# Generated by Django 4.1.2 on 2023-06-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alimentos_imagen_collares_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_alimento',
            fields=[
                ('id_tipo_alimento', models.AutoField(db_column='idTipoAlimento', primary_key=True, serialize=False)),
                ('tipo_alimento', models.CharField(max_length=20)),
            ],
        ),
    ]
