# Generated by Django 4.1.2 on 2023-06-22 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_tipo_alimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_juguete',
            fields=[
                ('id_tipo_juguete', models.AutoField(db_column='idTipoJuguete', primary_key=True, serialize=False)),
                ('tipo_juguete', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='juguetes',
            name='id_tipo_juguete',
            field=models.ForeignKey(db_column='idTipoJuguete', default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.tipo_juguete'),
        ),
    ]
