# Generated by Django 4.1.2 on 2023-06-22 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0011_remove_juguetes_id_tipo_juguete_juguetes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='juguetes',
            name='id_tipo_juguete',
            field=models.ForeignKey(db_column='idTipoJuguete', default=0, on_delete=django.db.models.deletion.CASCADE, to='venta.tipo_juguete'),
        ),
    ]
