# Generated by Django 4.1.2 on 2023-06-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0013_remove_juguetes_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguetes',
            name='id_tipo_juguete',
            field=models.ForeignKey(db_column='idTipoJuguete', on_delete=django.db.models.deletion.CASCADE, to='venta.tipo_juguete'),
        ),
    ]
