# Generated by Django 4.1.2 on 2023-06-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0015_juguetes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='juguetes',
            name='precio',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
