# Generated by Django 4.1.2 on 2023-06-22 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venta', '0016_juguetes_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('precio', models.CharField(default='$', max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/juguetes')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id_tipo_producto', models.AutoField(db_column='idTipoProducto', primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Juguetes',
        ),
        migrations.DeleteModel(
            name='Tipo_juguete',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipo_producto',
            field=models.ForeignKey(db_column='idTipoProducto', on_delete=django.db.models.deletion.CASCADE, to='venta.tipo_producto'),
        ),
    ]
