# Generated by Django 4.1.2 on 2023-06-22 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venta', '0018_remove_alimentos_author_remove_collares_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('precio', models.CharField(default='$', max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/prod_pop')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tipo_producto', models.ForeignKey(db_column='idTipoProducto', on_delete=django.db.models.deletion.CASCADE, to='venta.tipo_producto')),
            ],
        ),
    ]
