# Generated by Django 4.1.2 on 2023-06-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0021_alter_producto_id_tipo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_tipo_producto',
            field=models.ForeignKey(db_column='idTipoProducto', on_delete=django.db.models.deletion.CASCADE, to='venta.tipo_producto'),
        ),
    ]
