# Generated by Django 4.1.2 on 2023-06-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0022_alter_producto_id_tipo_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='text',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='author',
        ),
    ]
