# Generated by Django 4.1.2 on 2023-06-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0023_rename_text_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.ImageField(default=0, max_length=200, upload_to=''),
        ),
    ]
