# Generated by Django 4.1.2 on 2023-06-25 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0031_alter_producto_id_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(null=True)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/producto')),
            ],
        ),
        migrations.AlterField(
            model_name='tipo_producto',
            name='id_tipo_producto',
            field=models.AutoField(db_column='idTipoProducto', default=0, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='productos',
            name='id_tipo_producto',
            field=models.ForeignKey(db_column='idTipoProducto', default=0, on_delete=django.db.models.deletion.CASCADE, to='venta.tipo_producto'),
        ),
    ]
