# Generated by Django 4.1.2 on 2023-06-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0032_productos_alter_tipo_producto_id_tipo_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(null=True)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/producto')),
                ('id_tipo_producto', models.ForeignKey(db_column='idTipoProducto', on_delete=django.db.models.deletion.CASCADE, to='venta.tipo_producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
