# Generated by Django 4.1.2 on 2023-06-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0033_producto_delete_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
